name: tensorflow-gpu-1.5-py36
channels:
- defaults
dependencies:
- certifi=2016.2.28=py36_0
- pip=9.0.1=py36_1
- python=3.6.2=0
- setuptools=36.4.0=py36_1
- vc=14=0
- vs2015_runtime=14.0.25420=0
- wheel=0.29.0=py36_0
- wincertstore=0.2=py36_0
- pip:
  - absl-py==0.1.10
  - bleach==1.5.0
  - html5lib==0.9999999
  - markdown==2.6.11
  - numpy==1.14.0
  - protobuf==3.5.1
  - six==1.11.0
  - tensorflow==1.5.0
  - tensorflow-tensorboard==1.5.1
  - werkzeug==0.14.1
